#16. Guarde en dos variables de listas diferentes los siguientes elementos: [“amarillo“, “azul“, “violeta“] y [“zapallo“, “tomate“, “limón“] Genere una nueva lista que sea la concatenación de ambas, le debería quedar [“amarillo“, “azul“, “violeta“, “zapallo“, “tomate“, “limón“]

lista1 = ["amarillo", "azul", "violeta"]
lista2 = ["zapallo", "tomate", "limón"]

nueva_lista = lista1 + lista2

print(nueva_lista)
